# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nctkJzWjh_LyLLoesL0QHkv5LYvqv2QF
"""

import os
import cv2
import torch
import random
from torch.utils.data import Dataset







class SaliencyDataset(Dataset):
    def __init__(self, image_dir, mask_dir, image_list):
        self.image_dir = image_dir
        self.mask_dir = mask_dir
        self.images = image_list

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_name = self.images[idx]

        img_path = os.path.join(self.image_dir, img_name)
        mask_path = os.path.join(self.mask_dir, img_name)

        image = cv2.imread(img_path)
        image = cv2.resize(image, (128,128))
        image = image / 255.0

        mask = cv2.imread(mask_path, 0)
        mask = cv2.resize(mask, (128,128))
        mask = mask / 255.0


        if random.random() > 0.5:
            image = cv2.flip(image, 1)
            mask = cv2.flip(mask, 1)

        image = torch.tensor(image).permute(2,0,1).float()
        mask = torch.tensor(mask).unsqueeze(0).float()

        return image, mask