# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sp-lxkzIBdMI-8mOWNXFYNcjWGAKTQrv
"""

import torch
import os
from torch.utils.data import DataLoader
from sklearn.model_selection import train_test_split
import torch.nn.functional as F

from data_loader import SaliencyDataset
from sod_model import SimpleSOD




#loss

def iou(pred, target):
    intersection = (pred * target).sum()
    union = pred.sum() + target.sum() - intersection
    return (intersection + 1e-6) / (union + 1e-6)

def total_loss(pred, target):
    bce = F.binary_cross_entropy(pred, target)
    return bce + 0.5 * (1 - iou(pred, target))